- name: restart c*
  sudo: true
  service: name=cassandra state=restarted

- name: restart redis
  sudo: true
  service: name=redis-server state=restarted

- name: restart circus
  sudo: true
  service: name=circus state=restarted