---
- include: cassandra.yml

- name: install CMB pre reqs
  sudo: true
  tags: packages
  apt: pkg=$item state=latest update_cache=yes
  with_items:
    - redis-server

- name: cmb_dir
  sudo: true
  register: cmb_dir
  stat: path=/opt/cmb
  
- name: cmb is installed?
  set_fact: 
    cmb_not_installed: cmb_dir.stat.isdir is undefined or cmb_dir.stat.isdir == false 
    cmb_installed: cmb_dir.stat.isdir is defined and cmb_dir.stat.isdir == true 

- name: Download cmb binary
  get_url: url=$cmb_url dest=/opt/src/cmb.tar.gz mode=0600

- name: untar CMB
  shell: tar -xf /opt/src/cmb.tar.gz chdir=/opt/src
  when: cmb_not_installed

- name: move cmb to opt
  shell: cp -R /opt/src/cmb /opt/cmb
  when: cmb_not_installed

- name: place c* test
  copy: src=checkcmb.cql dest=/opt/cmb/checkcmb.cql

- name: if schema installed?
  shell: cassandra-cli -h localhost -f checkcmb.cql chdir=/opt/cmb
  ignore_errors: true
  register: schema_inst

- name: place c* schema
  copy: src=cass.schema dest=/opt/cmb/cass.schema
  when: schema_inst.rc == 4

- name: load c* schema
  shell: cassandra-cli -h localhost -f cass.schema chdir=/opt/cmb
  when: schema_inst.rc == 4

- name: configure redis
  sudo: true
  lineinfile: dest=/etc/redis/redis.conf line='$item' state=absent regexp=^save
  with_items:
    - 'save 900 1'
    - 'save 300 10'
    - 'save 60 10000'
  notify: restart redis

- name: add proc to circus
  sudo: true
  copy: src=cmb.ini dest=/etc/circus/conf.d/cmb.ini
  notify: restart circus
