---
- name: Install the unix basics
  sudo: true
  tags: repos
  apt: pkg=$item state=latest update_cache=yes
  with_items:
    - build-essential
    - tmux
    - emacs
    - traceroute
    - htop
    - ntop
    - python-software-properties
    - software-properties-common
    - strace
    - gdb

